import { MouseEventHandler } from "react";
import { ancestorHavingClass, failIfNull } from "../../utils";
import classNames from "classnames";

/** Mechanism to provide a "focus group", which is a collection of
 * component instances where focus can be sent to any item in that
 * collection using the arrow keys, but Tab moves focus out of the group
 * and on to the next "major section" of the interface.   I.e.,
 * conceptually, the group of items receives focus as a unit.  Tabbing
 * into and out of the unit remembers a "bookmarked" item within the
 * collection (see below).
 *
 * A focus group is identified by a string "key".  Each focus group has
 * a "bookmark", which is an index identifying the most-recently-focused
 * item within its collection.  All bookmarks start at zero.  Sometimes
 * a bookmark might refer to a non-existent item, so a focus group can
 * also have a "fallback" element, typically an "Add" button for that
 * collection.  The mechanism attempts to respond correctly to deletion
 * of an item within the group; see `focusBookmarkedItem()` method.
 *
 * There is some special-case handling for a nested collection such as
 * the nested accordion (details/summary) of the `HelpSidebar`.  This
 * shows up in the concept of a "navigable" item, which is one which
 * should be reachable via arrow-key presses.  In the motivating case of
 * the HelpSidebar items, headings are always navigable, and individual
 * help items are navigable if their containing section is open.
 *
 * Usage:
 *
 * The "container" element for the focus-group should be given three
 * things, as follows.  The container need not be the direct parent of
 * the items, just an ancestor.
 *
 * * The class `kFocusGroupContainerClassName` (that's an exported
 *   constant, not the literal classname).  Typically users will want to
 *   add additional classes, so a convenience function
 *   `focusGroupContainerClass()` combines its argument with this
 *   constant.
 *
 * * A ref callback generated by `containerRefCallback()`.  This handles
 *   keydown events, and also two-stage focus requests (such as when
 *   focus should be sent to the first sound of a sprite, but the
 *   "Sounds" tab is not displayed at the time the user makes the
 *   gesture).
 *
 * * A "data-grouped-focus-key" attribute giving the key for this focus
 *   group, uniquely identifying the group, as explained above.
 *
 * See `AppearancesList` for an example of a focus-group container.
 *
 * The "item" elements are those which can receive focus, so are often
 * `CaptiveContextMenu.Container` instances. They should be given two
 * things:
 *
 * * The class `kFocusGroupItemClassName`.
 *
 * * An `onClick` handler of `groupedFocusManager.onItemClick`.
 *
 * See `AssetCard` for an example of a focus-group item.
 *
 * A "fallback" descendant (which receives focus when it is desired to
 * give focus to an item within a particular container but that
 * container has no items) can be identified by giving it the
 * `kFocusGroupFallbackClassName` class.
 * */

export const kFocusGroupContainerClassName = "focus-group__container";
export const kFocusGroupItemClassName = "focus-group__item";
export const kFocusGroupFallbackClassName = "focus-group__fallback";

function funOrNop(
  mFun: ((elt: HTMLElement) => void) | undefined
): (mElt: HTMLElement | undefined) => void {
  if (mFun == null) {
    return (_mElt) => void 0;
  } else {
    return (mElt) => {
      if (mElt != null) {
        mFun(mElt);
      }
    };
  }
}

/** Create class-names string for a focus-group container from the base
 * container class plus the given `extraClassname`. */
export function focusGroupContainerClass(extraClassname?: string): string {
  return classNames(kFocusGroupContainerClassName, extraClassname);
}

/** Create class-names string for a focus-group item from the base
 * container class plus the given `extraClassname`. */
export function focusGroupItemClass(extraClassname: string): string {
  return classNames(kFocusGroupItemClassName, extraClassname);
}

/** Return whether `elt` is NOT inside a closed `<details>` element.
 * Only works for the particular case we need, which is a
 * HelpSidebarSection.
 * */
function isNavigable(elt: HTMLElement): boolean {
  if (elt.tagName !== "SUMMARY") {
    return true;
  }

  const grandParent = elt.parentElement?.parentElement;
  if (grandParent == null || grandParent.tagName !== "DETAILS") {
    return true;
  }

  return (grandParent as HTMLDetailsElement).open;
}

/** Given a target element `elt`, return a suitable element to receive
 * focus.  Usually the "suitable element" is `elt` itself, but if `elt`
 * is a SUMMARY element whose *grandparent* is a *closed* DETAILS
 * element, the "suitable element" is instead the SUMMARY child of that
 * (grandparent) closed DETAILS element.
 *
 * This handles the case in the nested HelpSidebar where focus was on a
 * particular help item, but, while a different actor-kind was active,
 * the section containing that help item was closed by the user.  Focus
 * then goes to the section summary.
 * */
function eltOrSectionSummary(elt: HTMLElement): HTMLElement {
  if (elt.tagName !== "SUMMARY") {
    return elt;
  }

  const grandParent = elt.parentElement?.parentElement;
  if (grandParent == null || grandParent.tagName !== "DETAILS") {
    return elt;
  }

  const detailsElt = grandParent as HTMLDetailsElement;
  if (detailsElt.open) {
    return elt;
  }

  const summaryChild = failIfNull(
    detailsElt.firstChild,
    "<details> has no child"
  );
  if (summaryChild.nodeType !== Node.ELEMENT_NODE) {
    throw new Error("<details> has non-element as first child");
  }

  const summaryElt = summaryChild as HTMLElement;
  if (summaryElt.tagName !== "SUMMARY") {
    throw new Error("<details> has non-<summary> as first child");
  }

  return summaryElt;
}

/** If a focus-group item has a captive context menu, then we want to
 * NOT respond to keypresses when that menu is open.  The
 * captive-context-menu logic gives the captive-context-menu container
 * element a particular class to signal that the menu is open.  This
 * function tests for the presence of such a suppressing element.
 *
 * This is rather more coupled than would be ideal; should we revisit
 * the design? */
function containsSuppressingItem(elt: HTMLElement) {
  const mSuppressingItem = elt.querySelector<HTMLElement>(
    `:scope [data-suppress-focus-group-navigation]`
  );
  return mSuppressingItem != null;
}

export const focusGroupNavigationSuppression = (() => {
  const onFocus = (ev: React.FocusEvent) => {
    const elt = ev.target as HTMLElement;
    elt.dataset.suppressFocusGroupNavigation = "yes";
  };

  const onBlur = (ev: React.FocusEvent) => {
    const elt = ev.target as HTMLElement;
    delete elt.dataset.suppressFocusGroupNavigation;
  };

  return { onFocus, onBlur };
})();

export type ReorderDirection = "earlier" | "later";
type ReorderFun = (itemElt: HTMLElement, direction: ReorderDirection) => void;

const kDefaultOnReorder = (_elt: HTMLElement, _dir: ReorderDirection) => void 0;

export type ContainerRefCallbackOptions = Partial<{
  onFocusFromKeyboard: (elt: HTMLElement) => void;
  onFocusFromPendingRequest: (elt: HTMLElement) => void;
  onReorder: ReorderFun;
  onActivate: (elt: HTMLElement) => void;
  preventDefaultAfterOnActivate: boolean;
}>;

type FocusBookmarkedItemOutcome =
  | { kind: "bookmarked" | "last" | "fallback"; elt: HTMLElement }
  | { kind: "none" };

type BookmarkMaybeFocusOptions = {
  doFocus: boolean;
};

const kBookmarkMaybeFocusOptionsDefaults: BookmarkMaybeFocusOptions = {
  doFocus: true,
};

function effectiveBookmarkMaybeFocusOptions(
  options?: Partial<BookmarkMaybeFocusOptions>
): BookmarkMaybeFocusOptions {
  return Object.assign({}, kBookmarkMaybeFocusOptionsDefaults, options ?? {});
}

export class GroupedFocusManager {
  bookmarkFromKey_: Map<string, number>;
  pendingKey: string | null;
  onItemClick: MouseEventHandler<HTMLElement>;

  constructor() {
    this.bookmarkFromKey_ = new Map<string, number>();
    this.pendingKey = null;
    this.onItemClick = (evt) => {
      this.bookmarkItem(evt.currentTarget);
    };
  }

  ////////////////////////////////////////////////////////////////////////

  /** Mechanism for two-stage focus.  Motivating use case is when the
   * user activates the dropdown-menu for a sprite but without
   * activating that sprite.  The user then chooses, say, "Go to
   * sounds".  We need to rerender the IDE for the Sounds of that
   * Sprite, and only then can we send focus to the first sound.  The
   * focus request is "pending" until a focus-group with the correct key
   * is rendered. */

  setPendingKey(targetKey: string) {
    if (this.pendingKey != null) {
      console.warn(
        "GroupedFocusManager.setPendingKey(): Discarding",
        this.pendingKey,
        "to replace with",
        targetKey
      );
    }
    this.pendingKey = targetKey;
  }

  acquirePendingKey(targetKey: string) {
    const wanted = this.pendingKey === targetKey;
    if (wanted) {
      this.pendingKey = null;
      return true;
    } else {
      return false;
    }
  }

  ////////////////////////////////////////////////////////////////////////

  static containedItemElts(elt: HTMLElement): Array<HTMLElement> {
    return Array.from(
      elt.getElementsByClassName(kFocusGroupItemClassName)
    ) as Array<HTMLElement>;
  }

  static keyFromElt(elt: HTMLElement): string {
    const mKey = elt.dataset.groupedFocusKey;
    if (mKey == null) {
      throw new Error("elt has no groupedFocusKey data attr");
    }
    return mKey;
  }

  static itemContext(containerElt: HTMLElement, itemElt: HTMLElement) {
    const allItems = GroupedFocusManager.containedItemElts(containerElt);
    const mIndex = allItems.findIndex((elt) => elt === itemElt);
    if (mIndex === -1) {
      throw new Error("itemElt not found in container");
    }
    return { allItems, index: mIndex };
  }

  static itemIndex(containerElt: HTMLElement, itemElt: HTMLElement): number {
    return GroupedFocusManager.itemContext(containerElt, itemElt).index;
  }

  /** Retrieve the bookmark (index into array of items) for the given
   * `key`.  If no such bookmark exists, set it to 0 and return it. */
  bookmarkFromKey(key: string): number {
    const mBookmarkIndex = this.bookmarkFromKey_.get(key);
    if (mBookmarkIndex == null) {
      this.bookmarkFromKey_.set(key, 0);
      return 0;
    } else {
      return mBookmarkIndex;
    }
  }

  /** Set the bookmark (index into array of items) for the given `key`
   * to the given `index`. */
  setBookmark(key: string, index: number) {
    this.bookmarkFromKey_.set(key, index);
  }

  /** Set the `tabIndex` attribute on each of the given `items`, such
   * that the item at index `bookmarkIndex` is part of the tab order
   * (via `tabIndex = 0`) and the others are programmatically focusable
   * only (via `tabIndex = -1`). */
  setTabFocusability(items: Array<HTMLElement>, bookmarkIndex: number) {
    items.forEach((item, itemIdx) => {
      item.tabIndex = itemIdx === bookmarkIndex ? 0 : -1;
    });
  }

  /** Set the `tabIndex` attribute of all the item descendents of the
   * given container `elt` according to the bookmark stored for the key
   * of that container. */
  setContainerTabFocusability(elt: HTMLElement) {
    const items = GroupedFocusManager.containedItemElts(elt);
    const key = GroupedFocusManager.keyFromElt(elt);
    const bookmarkIndex = this.bookmarkFromKey(key);
    this.setTabFocusability(items, bookmarkIndex);
  }

  /** Make the given `itemElt` within the given `containerElt` be the
   * bookmarked one, and also, by default, give it focus.  To just set
   * the bookmark, and not focus the newly-bookmarked item, include
   * `doFocus: false` in `options`. */
  bookmarkMaybeFocus(
    containerElt: HTMLElement,
    itemElt: HTMLElement,
    options?: Partial<BookmarkMaybeFocusOptions>
  ) {
    const effectiveOptions = effectiveBookmarkMaybeFocusOptions(options);

    const key = GroupedFocusManager.keyFromElt(containerElt);
    const itemContext = GroupedFocusManager.itemContext(containerElt, itemElt);
    this.setBookmark(key, itemContext.index);
    this.setTabFocusability(itemContext.allItems, itemContext.index);

    if (effectiveOptions.doFocus) {
      itemElt.focus();
    }
  }

  resolvedContainerAndKey(containerEltOrKey: HTMLElement | string) {
    // For both values, allow null or undefined; caller must handle this
    // situation, which is probably an error.

    const containerElt =
      containerEltOrKey instanceof HTMLElement
        ? containerEltOrKey
        : this.maybeContainerForKey(containerEltOrKey);

    const key =
      containerEltOrKey instanceof HTMLElement
        ? containerEltOrKey.dataset.groupedFocusKey
        : containerEltOrKey;

    return { containerElt, key };
  }

  /** Bookmark and focus the item descendent (of a specified container
   * element) at the given `index` within the array of navigable
   * descendants.  The container can be specified either by directly
   * supplying an `HTMLElement`, or by supplying the string key
   * identifying it.
   *
   * If the given `index` is negative, interpret it as an offset from
   * the end of the array of navigable descendant items.
   *
   * TODO: Should we simplify to just "first" or "last"?  Those are the
   * only values which are ever used currently. */
  focusAbsoluteItem(
    containerEltOrKey: HTMLElement | string,
    index: number
  ): HTMLElement | undefined {
    const { containerElt } = this.resolvedContainerAndKey(containerEltOrKey);
    if (containerElt == null) {
      console.warn("not a valid container:", containerEltOrKey);
      return;
    }

    const allItems = GroupedFocusManager.containedItemElts(containerElt);
    const navigableItems = allItems.filter(isNavigable);

    if (index < 0) {
      index += navigableItems.length;
    }

    const newFocusedItem = navigableItems[index];
    if (newFocusedItem == null) {
      console.warn(
        `bad index ${index} re navigable descendants of ${containerElt}`
      );
      return;
    }

    this.bookmarkMaybeFocus(containerElt, newFocusedItem);
    return newFocusedItem;
  }

  static nItemsInGroup(containerElt: HTMLElement) {
    return GroupedFocusManager.containedItemElts(containerElt).length;
  }

  callOnReorderFun(
    containerElt: HTMLElement,
    reorderFun: ReorderFun,
    reorderDir: ReorderDirection
  ) {
    const key = containerElt.dataset.groupedFocusKey;
    if (key == null) {
      console.warn("container element has no key", containerElt);
      return;
    }

    const allItems = GroupedFocusManager.containedItemElts(containerElt);
    const bookmark = this.bookmarkFromKey(key);
    const bookmarkedElt = allItems[bookmark];
    if (bookmarkedElt == null) {
      const message =
        `key "${key}" is for container with ${allItems.length} items` +
        ` but bookmark ${bookmark} points to null`;
      console.warn(message);
      return;
    }

    reorderFun(bookmarkedElt, reorderDir);
  }

  /** Bookmark and, by default, focus the navigable item descendent of a
   * specified container element which is the given `offset` after the
   * currently-bookmarked item.  (So if `offset` is negative, this moves
   * the bookmark earlier in the list.)  The container can be specified
   * either by directly supplying an `HTMLElement`, or by supplying the
   * string key identifying it.
   *
   * To just bookmark (and not focus) the item, include `doFocus: false`
   * in `options`.
   *
   * Return either `undefined` (in the case of error or attempt to move
   * outside the range of valid items) or the `HTMLElement` to which the
   * focus was moved.
   */
  bookmarkMaybeFocusOffsetItem(
    containerEltOrKey: HTMLElement | string,
    offset: number,
    options?: Partial<BookmarkMaybeFocusOptions>
  ): HTMLElement | undefined {
    const { containerElt, key } =
      this.resolvedContainerAndKey(containerEltOrKey);
    if (containerElt == null || key == null) {
      console.warn("not a valid container/key:", containerElt, key);
      return;
    }

    const allItems = GroupedFocusManager.containedItemElts(containerElt);
    const navigableItems = allItems.filter(isNavigable);
    const bookmark = this.bookmarkFromKey(key);
    const bookmarkedElt = allItems[bookmark];
    if (bookmarkedElt == null) {
      console.warn("bookmark gave invalid elt", key, bookmark);
      return;
    }

    const bookmarkedNavigableIndex = navigableItems.indexOf(bookmarkedElt);
    if (bookmarkedNavigableIndex === -1) {
      console.warn("bookmarked elt not found in navigable items");
      return;
    }

    const newBookmark = bookmarkedNavigableIndex + offset;
    const newBookmarkedItem = navigableItems[newBookmark];
    if (newBookmarkedItem == null) {
      // Moved outside list of navigable items.
      return;
    }

    this.bookmarkMaybeFocus(containerElt, newBookmarkedItem, options);
    return newBookmarkedItem;
  }

  /** Give focus to the bookmarked descendant of the given
   * `containerElt`, if possible.  Doing so is not possible if the
   * bookmark (i.e., index) is an invalid index into the array of items.
   * This can happen:
   *
   * * If the list is empty, and we are trying to use the default 0
   *   bookmark.  In this case, focus the "fallback" descendant, if one
   *   exists.
   *
   * * Suppose, e.g., a container has four items, the fourth one is the
   *   bookmarked one (so the bookmark is `3`), and then that fourth
   *   item has been deleted.  We instead focus the third item.  If a
   *   container contains only one item and it is deleted, we focus the
   *   fallback descendant (if one exists).
   * */
  focusBookmarkedItem(containerElt: HTMLElement): FocusBookmarkedItemOutcome {
    const key = GroupedFocusManager.keyFromElt(containerElt);

    const items = GroupedFocusManager.containedItemElts(containerElt);
    const bookmark = this.bookmarkFromKey(key);
    const mBookmarkedItem = items[bookmark];
    if (mBookmarkedItem != null) {
      const focusTarget = eltOrSectionSummary(mBookmarkedItem);
      this.bookmarkMaybeFocus(containerElt, focusTarget);
      return { kind: "bookmarked", elt: focusTarget };
    }

    const mLastItem = items[items.length - 1];
    if (mLastItem != null) {
      const focusTarget = eltOrSectionSummary(mLastItem);
      this.bookmarkMaybeFocus(containerElt, focusTarget);
      return { kind: "last", elt: focusTarget };
    }

    const fallbacks = containerElt.getElementsByClassName(
      kFocusGroupFallbackClassName
    );
    const mFallback = fallbacks[0] as HTMLElement | null;
    if (mFallback != null) {
      mFallback.focus();
      return { kind: "fallback", elt: mFallback };
    }

    console.warn("No descendant item or fallback found for", key);
    return { kind: "none" };
  }

  /** Find the container with the given focus-group `key`, if such a
   * container exists.
   * */
  maybeContainerForKey(key: string) {
    return document.querySelector<HTMLElement>(
      `.${kFocusGroupContainerClassName}[data-grouped-focus-key="${key}"]`
    );
  }

  /** If a focus-group container with the given `key` exists, then focus
   * its bookmarked item; if not, note a pending request to focus that
   * container's bookmarked child when that container is rendered, which
   * should be imminently. */
  focusBookmarkedItemOrQueueRequest(key: string) {
    const mContainer = this.maybeContainerForKey(key);
    if (mContainer != null) {
      this.focusBookmarkedItem(mContainer);
    } else {
      this.setPendingKey(key);
    }
  }

  /** Bookmark the given item `elt` and update the `tabIndex` attribute
   * of it and its siblings within the containing focus-group container.
   * */
  bookmarkItem(elt: HTMLElement) {
    const containerElt = ancestorHavingClass(
      elt,
      kFocusGroupContainerClassName
    );
    const itemElt = ancestorHavingClass(elt, kFocusGroupItemClassName);
    const key = GroupedFocusManager.keyFromElt(containerElt);
    const eltIdx = GroupedFocusManager.itemIndex(containerElt, itemElt);
    this.bookmarkItemByKeyAndIndex(key, eltIdx, containerElt);
  }

  /** Bookmark the element at the given `eltIndex` given the `key`, and
   * update the tab-index attribute of the now-bookmarked element and
   * its siblings.
   *
   * Optionally, the given `containerElt` is assumed to be the container
   * for that key; if not provided, it is searched for.
   * */
  bookmarkItemByKeyAndIndex(
    key: string,
    eltIndex: number,
    containerElt?: HTMLElement | null
  ) {
    containerElt ??= this.maybeContainerForKey(key);
    if (containerElt == null) {
      console.warn(`bookmarkItemByKeyAndIndex(): no container for "${key}"`);
      return;
    }

    this.setBookmark(key, eltIndex);
    this.setContainerTabFocusability(containerElt);
  }

  /** Ensure that the focus-group with the given `key` has a bookmark
   * which is in range for the items within the focus-group.  If this
   * already holds, do nothing.  Otherwise, find the first item in the
   * focus-group for which `itemShouldBecomeBookmarked()` returns
   * `true`, and set the focus-group's bookmark to that item's index. */
  ensureBookmarkInRange(
    key: string,
    itemShouldBecomeBookmarked: (elt: HTMLElement) => boolean
  ) {
    const containerElt = this.maybeContainerForKey(key);
    if (containerElt == null) {
      console.warn(`ensureBookmarkValid(): no container for "${key}"`);
      return;
    }

    const bookmark = this.bookmarkFromKey(key);
    const items = GroupedFocusManager.containedItemElts(containerElt);
    if (bookmark >= 0 && bookmark < items.length) {
      return;
    }

    const correctedBookmark = items.findIndex(itemShouldBecomeBookmarked);
    if (correctedBookmark === -1) {
      console.warn(`ensureBookmarkValid(): no fallback item found`);
      return;
    }

    this.bookmarkItemByKeyAndIndex(key, correctedBookmark, containerElt);
  }

  /** If `enabled`, return a ref callback function (suitable for an
   * element whose parent is focus-group item element) which bookmarks
   * and focuses that item.  (This is a bit clunky; see usages.)
   * */
  bookmarkAndFocusItemIfNotableFun(enabled: boolean) {
    if (!enabled) return () => void 0;

    return (innerDiv: HTMLDivElement) => {
      if (innerDiv == null) return;

      const focusItemDiv = innerDiv.parentElement;
      if (focusItemDiv == null) return;

      if (!focusItemDiv.classList.contains(kFocusGroupItemClassName)) {
        console.warn("parent is not focus-group item", focusItemDiv);
      }

      this.bookmarkItem(focusItemDiv);
      focusItemDiv.focus();
    };
  }

  /** Return a freshly-made function to act as a ref callback for the
   * focus-group container element.  It attaches key handlers and also is
   * part of managing the two-stage focus-request mechanism (see docs just
   * before `setPendingKey()`). */
  containerRefCallback<ElementT extends HTMLElement>(
    opts?: ContainerRefCallbackOptions
  ) {
    opts ??= {};

    const onFocusFromKeyboard = funOrNop(opts.onFocusFromKeyboard);
    const onFocusFromPendingRequest = funOrNop(opts.onFocusFromPendingRequest);
    const onActivate = funOrNop(opts.onActivate);
    const preventDefaultAfterOnActivate =
      opts.preventDefaultAfterOnActivate ?? false;

    let onKeyDown: ((evt: KeyboardEvent) => void) | null = null;
    let eltWithHandler: HTMLElement | null = null;

    return (elt: ElementT | null) => {
      if (elt == null) {
        if (eltWithHandler != null && onKeyDown != null) {
          eltWithHandler.removeEventListener("keydown", onKeyDown);
        }
      } else {
        const key = GroupedFocusManager.keyFromElt(elt);

        this.setContainerTabFocusability(elt);
        if (eltWithHandler == null) {
          onKeyDown = (evt) => {
            // Do nothing if the user is navigating a dropdown menu.
            if (containsSuppressingItem(elt)) return;

            // Swallow arrows and home/end if focus is on the fallback
            // item (usually the "Add SOMETHING" button).
            const evtTarget = evt.target as HTMLElement;
            if (evtTarget.classList.contains(kFocusGroupFallbackClassName)) {
              switch (evt.key) {
                case "ArrowRight":
                case "ArrowDown":
                case "ArrowLeft":
                case "ArrowUp":
                case "Home":
                case "End":
                  evt.preventDefault();
              }
              return;
            }

            switch (evt.key) {
              case "ArrowRight":
              case "ArrowDown": {
                const mNewFocusedElt = this.bookmarkMaybeFocusOffsetItem(
                  elt,
                  1
                );
                onFocusFromKeyboard(mNewFocusedElt);
                evt.preventDefault();
                break;
              }

              case "ArrowLeft":
              case "ArrowUp": {
                const mNewFocusedElt = this.bookmarkMaybeFocusOffsetItem(
                  elt,
                  -1
                );
                onFocusFromKeyboard(mNewFocusedElt);
                evt.preventDefault();
                break;
              }

              case "Home": {
                const mNewFocusedElt = this.focusAbsoluteItem(elt, 0);
                onFocusFromKeyboard(mNewFocusedElt);
                break;
              }

              case "End": {
                const mNewFocusedElt = this.focusAbsoluteItem(elt, -1);
                onFocusFromKeyboard(mNewFocusedElt);
                break;
              }

              case " ":
              case "Enter": {
                onActivate(evtTarget);
                if (preventDefaultAfterOnActivate) {
                  evt.preventDefault();
                }
                break;
              }
            }
          };
          eltWithHandler = elt;
          elt.addEventListener("keydown", onKeyDown);

          const focusRequestPending = this.acquirePendingKey(key);
          if (focusRequestPending) {
            // For reasons I haven't got to the bottom of, if we
            // directly call focus() (via the focusBookmarkedItem()
            // method), the focus gets overridden when the focus-group
            // is in a just-rendered <Modal>.
            setTimeout(() => {
              const focusOutcome = this.focusBookmarkedItem(elt);
              if (focusOutcome.kind !== "none") {
                onFocusFromPendingRequest(focusOutcome.elt);
              }
            });
          }
        }
      }
    };
  }
}
