import { MouseEventHandler } from "react";
import { ancestorHavingClass, failIfNull } from "../../utils";
import classNames from "classnames";

/** Mechanism to provide a "focus group", which is a collection of
 * component instances where focus can be sent to any item in that
 * collection using the arrow keys, but Tab moves focus out of the group
 * and on to the next "major section" of the interface.   I.e.,
 * conceptually, the group of items receives focus as a unit.  Tabbing
 * into and out of the unit remembers a "bookmarked" item within the
 * collection (see below).
 *
 * A focus group is identified by a string "key".  Each focus group has
 * a "bookmark", which is an index identifying the most-recently-focused
 * item within its collection.  All bookmarks start at zero.  Sometimes
 * a bookmark might refer to a non-existent item, so a focus group can
 * also have a "fallback" element, typically an "Add" button for that
 * collection.  The mechanism attempts to respond correctly to deletion
 * of an item within the group; see `focusBookmarkedItem()` method.
 *
 * There is some special-case handling for a nested collection such as
 * the nested accordion (details/summary) of the `HelpSidebar`.  This
 * shows up in the concept of a "navigable" item, which is one which
 * should be reachable via arrow-key presses.  In the motivating case of
 * the HelpSidebar items, headings are always navigable, and individual
 * help items are navigable if their containing section is open.
 *
 * Usage:
 *
 * The "container" element for the focus-group should be given three
 * things, as follows.  The container need not be the direct parent of
 * the items, just an ancestor.
 *
 * * The class `kFocusGroupContainerClassName` (that's an exported
 *   constant, not the literal classname).  Typically users will want to
 *   add additional classes, so a convenience function
 *   `focusGroupContainerClass()` combines its argument with this
 *   constant.
 *
 * * A ref callback generated by `containerRefCallback()`.  This handles
 *   keydown events, and also two-stage focus requests (such as when
 *   focus should be sent to the first sound of a sprite, but the
 *   "Sounds" tab is not displayed at the time the user makes the
 *   gesture).
 *
 * * A "data-grouped-focus-key" attribute giving the key for this focus
 *   group, uniquely identifying the group, as explained above.
 *
 * See `AppearancesList` for an example of a focus-group container.
 *
 * The "item" elements are those which can receive focus, so are often
 * `CaptiveContextMenu.Container` instances. They should be given two
 * things:
 *
 * * The class `kFocusGroupItemClassName`.
 *
 * * An `onClick` handler of `groupedFocusManager.onItemClick`.
 *
 * See `AssetCard` for an example of a focus-group item.
 *
 * A "fallback" descendant (which receives focus when it is desired to
 * give focus to an item within a particular container but that
 * container has no items) can be identified by giving it the
 * `kFocusGroupFallbackClassName` class.
 * */

export const kFocusGroupContainerClassName = "focus-group__container";
export const kFocusGroupItemClassName = "focus-group__item";
export const kFocusGroupFallbackClassName = "focus-group__fallback";

/** Create class-names string for a focus-group container from the base
 * container class plus the given `extraClassname`. */
export function focusGroupContainerClass(extraClassname: string): string {
  return classNames(kFocusGroupContainerClassName, extraClassname);
}

/** Return whether `elt` is NOT inside a closed `<details>` element.
 * Only works for the particular case we need, which is a
 * HelpSidebarSection.
 * */
function isNavigable(elt: HTMLElement): boolean {
  if (elt.tagName !== "SUMMARY") {
    return true;
  }

  const grandParent = elt.parentElement?.parentElement;
  if (grandParent == null || grandParent.tagName !== "DETAILS") {
    return true;
  }

  return (grandParent as HTMLDetailsElement).open;
}

/** Given a target element `elt`, return a suitable element to receive
 * focus.  Usually the "suitable element" is `elt` itself, but if `elt`
 * is a SUMMARY element whose *grandparent* is a *closed* DETAILS
 * element, the "suitable element" is instead the SUMMARY child of that
 * (grandparent) closed DETAILS element.
 *
 * This handles the case in the nested HelpSidebar where focus was on a
 * particular help item, but, while a different actor-kind was active,
 * the section containing that help item was closed by the user.  Focus
 * then goes to the section summary.
 * */
function eltOrSectionSummary(elt: HTMLElement): HTMLElement {
  if (elt.tagName !== "SUMMARY") {
    return elt;
  }

  const grandParent = elt.parentElement?.parentElement;
  if (grandParent == null || grandParent.tagName !== "DETAILS") {
    return elt;
  }

  const detailsElt = grandParent as HTMLDetailsElement;
  if (detailsElt.open) {
    return elt;
  }

  const summaryChild = failIfNull(
    detailsElt.firstChild,
    "<details> has no child"
  );
  if (summaryChild.nodeType !== Node.ELEMENT_NODE) {
    throw new Error("<details> has non-element as first child");
  }

  const summaryElt = summaryChild as HTMLElement;
  if (summaryElt.tagName !== "SUMMARY") {
    throw new Error("<details> has non-<summary> as first child");
  }

  return summaryElt;
}

/** If a focus-group item has a captive context menu, then we want to
 * NOT respond to keypresses when that menu is open.  The
 * captive-context-menu logic gives the captive-context-menu container
 * element a particular class to signal that the menu is open.  This
 * function tests for the presence of such a suppressing element.
 *
 * This is rather more coupled than would be ideal; should we revisit
 * the design? */
function containsSuppressingItem(elt: HTMLElement) {
  const mSuppressingItem = elt.querySelector<HTMLElement>(
    `:scope .${kFocusGroupItemClassName}[data-suppress-focus-group-navigation]`
  );
  return mSuppressingItem != null;
}

type FocusBookmarkedItemOutcome =
  | { kind: "bookmarked" | "last" | "fallback"; elt: HTMLElement }
  | { kind: "none" };

export class GroupedFocusManager {
  bookmarkFromKey_: Map<string, number>;
  pendingKey: string | null;
  onItemClick: MouseEventHandler<HTMLElement>;

  constructor() {
    this.bookmarkFromKey_ = new Map<string, number>();
    this.pendingKey = null;
    this.onItemClick = (evt) => {
      this.bookmarkItem(evt.currentTarget);
    };
  }

  ////////////////////////////////////////////////////////////////////////

  /** Mechanism for two-stage focus.  Motivating use case is when the
   * user activates the dropdown-menu for a sprite but without
   * activating that sprite.  The user then chooses, say, "Go to
   * sounds".  We need to rerender the IDE for the Sounds of that
   * Sprite, and only then can we send focus to the first sound.  The
   * focus request is "pending" until a focus-group with the correct key
   * is rendered. */

  setPendingKey(targetKey: string) {
    if (this.pendingKey != null) {
      console.warn(
        "GroupedFocusManager.setPendingKey(): Discarding",
        this.pendingKey,
        "to replace with",
        targetKey
      );
    }
    this.pendingKey = targetKey;
  }

  acquirePendingKey(targetKey: string) {
    const wanted = this.pendingKey === targetKey;
    if (wanted) {
      this.pendingKey = null;
      return true;
    } else {
      return false;
    }
  }

  ////////////////////////////////////////////////////////////////////////

  static containedItemElts(elt: HTMLElement): Array<HTMLElement> {
    return Array.from(
      elt.getElementsByClassName(kFocusGroupItemClassName)
    ) as Array<HTMLElement>;
  }

  static keyFromElt(elt: HTMLElement): string {
    const mKey = elt.dataset.groupedFocusKey;
    if (mKey == null) {
      throw new Error("elt has no groupedFocusKey data attr");
    }
    return mKey;
  }

  static itemContext(containerElt: HTMLElement, itemElt: HTMLElement) {
    const allItems = GroupedFocusManager.containedItemElts(containerElt);
    const mIndex = allItems.findIndex((elt) => elt === itemElt);
    if (mIndex === -1) {
      throw new Error("itemElt not found in container");
    }
    return { allItems, index: mIndex };
  }

  static itemIndex(containerElt: HTMLElement, itemElt: HTMLElement): number {
    return GroupedFocusManager.itemContext(containerElt, itemElt).index;
  }

  /** Retrieve the bookmark (index into array of items) for the given
   * `key`.  If no such bookmark exists, set it to 0 and return it. */
  bookmarkFromKey(key: string): number {
    const mBookmarkIndex = this.bookmarkFromKey_.get(key);
    if (mBookmarkIndex == null) {
      this.bookmarkFromKey_.set(key, 0);
      return 0;
    } else {
      return mBookmarkIndex;
    }
  }

  /** Set the bookmark (index into array of items) for the given `key`
   * to the given `index`. */
  setBookmark(key: string, index: number) {
    this.bookmarkFromKey_.set(key, index);
  }

  /** Set the `tabIndex` attribute on each of the given `items`, such
   * that the item at index `bookmarkIndex` is part of the tab order
   * (via `tabIndex = 0`) and the others are programmatically focusable
   * only (via `tabIndex = -1`). */
  setTabFocusability(items: Array<HTMLElement>, bookmarkIndex: number) {
    items.forEach((item, itemIdx) => {
      item.tabIndex = itemIdx === bookmarkIndex ? 0 : -1;
    });
  }

  /** Set the `tabIndex` attribute of all the item descendents of the
   * given container `elt` according to the bookmark stored for the key
   * of that container. */
  setContainerTabFocusability(elt: HTMLElement) {
    const items = GroupedFocusManager.containedItemElts(elt);
    const key = GroupedFocusManager.keyFromElt(elt);
    const bookmarkIndex = this.bookmarkFromKey(key);
    this.setTabFocusability(items, bookmarkIndex);
  }

  /** Make the given `itemElt` within the given `containerElt` be the
   * bookmarked one, and also give it focus. */
  bookmarkAndFocus(containerElt: HTMLElement, itemElt: HTMLElement) {
    const key = GroupedFocusManager.keyFromElt(containerElt);
    const itemContext = GroupedFocusManager.itemContext(containerElt, itemElt);
    this.setBookmark(key, itemContext.index);
    itemElt.focus();
    this.setTabFocusability(itemContext.allItems, itemContext.index);
  }

  /** Bookmark and focus the item descendent (of a specified container
   * element) at the given `index` within the array of navigable
   * descendants.  The container can be specified either by directly
   * supplying an `HTMLElement`, or by specifying the string key
   * identifying it.
   *
   * If the given `index` is negative, interpret it as an offset from
   * the end of the array of navigable descendant items.
   *
   * TODO: Should we simplify to just "first" or "last"?  Those are the
   * only values which are ever used currently. */
  focusAbsoluteItem(containerEltOrKey: HTMLElement | string, index: number) {
    const containerElt =
      containerEltOrKey instanceof HTMLElement
        ? containerEltOrKey
        : this.maybeContainerForKey(containerEltOrKey);

    if (containerElt == null) {
      console.warn("not a valid container:", containerEltOrKey);
      return;
    }

    const allItems = GroupedFocusManager.containedItemElts(containerElt);
    const navigableItems = allItems.filter(isNavigable);

    if (index < 0) {
      index += navigableItems.length;
    }

    const newFocusedItem = navigableItems[index];
    if (newFocusedItem == null) {
      console.warn(
        `bad index ${index} re navigable descendants of ${containerElt}`
      );
      return;
    }

    this.bookmarkAndFocus(containerElt, newFocusedItem);
  }

  static nItemsInGroup(containerElt: HTMLElement) {
    return GroupedFocusManager.containedItemElts(containerElt).length;
  }

  /** Bookmark and focus the navigable item descendent of the given
   * `containerElt` which is the given `offset` after the
   * currently-bookmarked item.  (So if `offset` is negative, this moves
   * the bookmark earlier in the list.)
   */
  focusOffsetItem(containerElt: HTMLElement, offset: number) {
    const allItems = GroupedFocusManager.containedItemElts(containerElt);
    const navigableItems = allItems.filter(isNavigable);
    const focusedElt = containerElt.querySelector<HTMLElement>(":scope :focus");
    if (focusedElt == null) {
      console.warn("no focused elt");
      return;
    }

    const focusedNavigableIndex = navigableItems.indexOf(focusedElt);
    if (focusedNavigableIndex === -1) {
      console.warn("focused elt not found in navigable items");
      return;
    }

    const newFocusIndex = focusedNavigableIndex + offset;
    const newFocusedItem = navigableItems[newFocusIndex];
    if (newFocusedItem == null) {
      // Moved outside list of navigable items.
      return;
    }

    this.bookmarkAndFocus(containerElt, newFocusedItem);
  }

  /** Give focus to the bookmarked descendant of the given
   * `containerElt`, if possible.  Doing so is not possible if the
   * bookmark (i.e., index) is an invalid index into the array of items.
   * This can happen:
   *
   * * If the list is empty, and we are trying to use the default 0
   *   bookmark.  In this case, focus the "fallback" descendant, if one
   *   exists.
   *
   * * Suppose, e.g., a container has four items, the fourth one is the
   *   bookmarked one (so the bookmark is `3`), and then that fourth
   *   item has been deleted.  We instead focus the third item.  If a
   *   container contains only one item and it is deleted, we focus the
   *   fallback descendant (if one exists).
   * */
  focusBookmarkedItem(containerElt: HTMLElement): FocusBookmarkedItemOutcome {
    const key = GroupedFocusManager.keyFromElt(containerElt);

    const items = GroupedFocusManager.containedItemElts(containerElt);
    const bookmark = this.bookmarkFromKey(key);
    const mBookmarkedItem = items[bookmark];
    if (mBookmarkedItem != null) {
      const focusTarget = eltOrSectionSummary(mBookmarkedItem);
      this.bookmarkAndFocus(containerElt, focusTarget);
      return { kind: "bookmarked", elt: focusTarget };
    }

    const mLastItem = items[items.length - 1];
    if (mLastItem != null) {
      const focusTarget = eltOrSectionSummary(mLastItem);
      this.bookmarkAndFocus(containerElt, focusTarget);
      return { kind: "last", elt: focusTarget };
    }

    const fallbacks = containerElt.getElementsByClassName(
      kFocusGroupFallbackClassName
    );
    const mFallback = fallbacks[0] as HTMLElement | null;
    if (mFallback != null) {
      mFallback.focus();
      return { kind: "fallback", elt: mFallback };
    }

    console.warn("No descendant item or fallback found for", key);
    return { kind: "none" };
  }

  /** Find the container with the given focus-group `key`, if such a
   * container exists.
   * */
  maybeContainerForKey(key: string) {
    return document.querySelector<HTMLElement>(
      `.${kFocusGroupContainerClassName}[data-grouped-focus-key="${key}"]`
    );
  }

  /** If a focus-group container with the given `key` exists, then focus
   * its bookmarked item; if not, note a pending request to focus that
   * container's bookmarked child when that container is rendered, which
   * should be imminently. */
  focusBookmarkedItemOrQueueRequest(key: string) {
    const mContainer = this.maybeContainerForKey(key);
    if (mContainer != null) {
      this.focusBookmarkedItem(mContainer);
    } else {
      this.setPendingKey(key);
    }
  }

  /** Bookmark the given item `elt` and update the `tabIndex` attribute
   * of it and its siblings within the containing focus-group container.
   * */
  bookmarkItem(elt: HTMLElement) {
    const containerElt = ancestorHavingClass(
      elt,
      kFocusGroupContainerClassName
    );
    const key = GroupedFocusManager.keyFromElt(containerElt);
    const eltIdx = GroupedFocusManager.itemIndex(containerElt, elt);
    this.setBookmark(key, eltIdx);
    this.setContainerTabFocusability(containerElt);
  }

  /** If `enabled`, return a ref callback function (suitable for an
   * element whose parent is focus-group item element) which bookmarks
   * and focuses that item.  (This is a bit clunky; see usages.)
   * */
  bookmarkAndFocusItemIfNotableFun(enabled: boolean) {
    if (!enabled) return () => void 0;

    return (innerDiv: HTMLDivElement) => {
      if (innerDiv == null) return;

      const focusItemDiv = innerDiv.parentElement;
      if (focusItemDiv == null) return;

      if (!focusItemDiv.classList.contains(kFocusGroupItemClassName)) {
        console.warn("parent is not focus-group item", focusItemDiv);
      }

      this.bookmarkItem(focusItemDiv);
      focusItemDiv.focus();
    };
  }

  /** Return a freshly-made function to act as a ref callback for the
   * focus-group container element.  It attaches key handlers and also is
   * part of managing the two-stage focus-request mechanism (see docs just
   * before `setPendingKey()`). */
  containerRefCallback<ElementT extends HTMLElement>() {
    let onKeyDown: ((evt: KeyboardEvent) => void) | null = null;
    let eltWithHandler: HTMLElement | null = null;

    return (elt: ElementT | null) => {
      if (elt == null) {
        if (eltWithHandler != null && onKeyDown != null) {
          eltWithHandler.removeEventListener("keydown", onKeyDown);
        }
      } else {
        const key = GroupedFocusManager.keyFromElt(elt);

        this.setContainerTabFocusability(elt);
        if (eltWithHandler == null) {
          onKeyDown = (evt) => {
            // Do nothing if the user is navigating a dropdown menu.
            if (containsSuppressingItem(elt)) return;

            switch (evt.key) {
              case "ArrowRight":
              case "ArrowDown":
                this.focusOffsetItem(elt, 1);
                evt.preventDefault();
                break;

              case "ArrowLeft":
              case "ArrowUp":
                this.focusOffsetItem(elt, -1);
                evt.preventDefault();
                break;

              case "Home":
                this.focusAbsoluteItem(elt, 0);
                break;

              case "End":
                this.focusAbsoluteItem(elt, -1);
                break;
            }
          };
          eltWithHandler = elt;
          elt.addEventListener("keydown", onKeyDown);

          const focusRequestPending = this.acquirePendingKey(key);
          if (focusRequestPending) {
            this.focusBookmarkedItem(elt);
          }
        }
      }
    };
  }
}
