"""
One-off tool to generate one big "monolithic" translations file for
easier working with the online POEditor system.

Usage, from root of pytch-webapp repo, as one line:

python tools/i18n/create_poeditor_file.py
  public/locales/en
  src/data/i18n/hsb-en.json
    > src/data/i18n/en.json

where `src/data/i18n/hsb-en.json` was generated by the one-off script
split_hsb_structure_vs_en.py (in this directory).

You can supply "/dev/null" (matched as a string) as the second
argument for a language which currently has no help-sidebar strings
file.
"""

import json, sys
from pathlib import Path

ns_files_dir = Path(sys.argv[1])

hsb_path = Path(sys.argv[2])

string_from_full_key: dict[str, str] = {}

# List copied from src/@types/resources.ts
namespaces = [
    "common",
    "assets",
    "demos",
    "errors",
    "flows",
    "ide",
    "notable-changes",
    "projects",
    "tutorials",
    "vm",
    "welcome",
]

for ns in namespaces:
    ns_file = ns_files_dir / f"{ns}.json"
    ns_prefix = ns_file.stem
    with ns_file.open("rt") as f_in:
        ns_dict: dict[str, str] | None = json.load(f_in)
    if not isinstance(ns_dict, dict):
        raise ValueError(f'expecting dict in "{ns_file}"')
    for ns_key, ns_str in ns_dict.items():
        if ns_key == "$RUBBISH$":
            continue
        full_key = f"{ns_prefix}.{ns_key}"
        string_from_full_key[full_key] = ns_str


if str(hsb_path) != "/dev/null":
    with hsb_path.open("rt") as f_in:
        help_strings: dict[str, str] = json.load(f_in)
        string_from_full_key.update(help_strings)

json.dump(string_from_full_key, sys.stdout, ensure_ascii=False, indent=2)
sys.stdout.write("\n")
