import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faHome,
  faCopy,
  faBook,
  faClipboard,
  faFileArchive,
  faInfoCircle,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faQuestionCircle,
  faExpand,
  faCompress,
  faPlay,
  faStop,
  faPlus,
  faArrowLeft,
  faImage,
  faCrop,
  faPencilAlt,
  faCaretDown,
  faCaretUp,
  faAngleUp,
  faAngleDown,
  faAnglesUp,
  faAnglesDown,
} from "@fortawesome/free-solid-svg-icons";

import { faTimesCircle } from "@fortawesome/free-regular-svg-icons";

library.add(
  faHome,
  faCopy,
  faBook,
  faClipboard,
  faFileArchive,
  faInfoCircle,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faQuestionCircle,
  faExpand,
  faCompress,
  faPlay,
  faStop,
  faPlus,
  faArrowLeft,
  faImage,
  faCrop,
  faPencilAlt,
  faCaretDown,
  faCaretUp,
  faAngleUp,
  faAngleDown,
  faAnglesUp,
  faAnglesDown,
  faTimesCircle
);
